jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

language: clojure
lein: lein2
script: lein do clean, cljsbuild once electron-dev, cljsbuild once frontend-dev, clean, cljsbuild once electron-release, cljsbuild once frontend-release
